#!/usr/bin/env bash
set -ex

ROOT_DIR="../data"
SUB_DIRS=$(find "$ROOT_DIR" -type d \( -name "pophys" -o -name "ophys" \))

echo $SUB_DIR
python -u run_capsule.py --input-dir $SUB_DIR --temp ../scratch --output-dir ../results
