#!/usr/bin/env bash
set -ex

ROOT_DIR="../data"

# Find the subdirectory
SUB_DIR=$(find "$ROOT_DIR" -type d -name "ophys")

# Check if subdirectory exists
if [ -z "$SUB_DIR" ]; then
    echo "Subdirectory not found in $ROOT_DIR"
    exit 1
fi

# Construct the JSON string
JSON_STRING='{"storage_path":"'"$SUB_DIR"'","tmp_dir":"../scratch"}'
echo $JSON_STRING

# python -u run_capsule.py --job-settings "$JSON_STRING"
