#!/usr/bin/env bash
set -ex

ROOT_DIR="../data"
# Find the subdirectory
ROOT_DIR="../data"
SUB_DIR=()
for dir in "$ROOT_DIR"/*/*phys; do
    if [ -d "$dir" ]; then
        SUB_DIR+=("$dir")
    fi
done

echo $SUB_DIR
python -u run_capsule.py --input-dir $SUB_DIR --temp ../scratch --output-dir ../results
